export type Organization = {
    id?: string,
    name: string,
    organization: string,
    type: string,
    image: string,
    shortDescription: string,
    city: string,
    state: string,
    site: string,
    contact?: string,
    facebook?: string,
    instagram?: string,
    whatsapp?: string,
}